service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  # - serverless-webpack
  - serverless-offline
  - serverless-step-functions
  - serverless-step-functions-offline

custom:
  stepFunctionsOffline:
    FirstLambda: firstLambda 
    SecondLambda: secondLambda 
    stepOne: firstLambda 
    stepTwo: secondLambda 

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  firstLambda:
      handler: handler.first
      name: TheFirstLambda
  secondLambda:
      handler: handler.second
      name: TheSecondLambda
stepFunctions:
  stateMachines:
    foo:
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt: FirstLambda
        States:
            FirstLambda:
              Type: Task
              Resource: arn:aws:lambda:eu-west-1:123456789:function:TheFirstLambda
              Next: SecondLambda
            SecondLambda:
              Type: Task
              Resource: arn:aws:lambda:eu-west-1:123456789:function:TheSecondLambda
              End: true